services:
  mongodb:
    image: mongo:6.0.16
    container_name: noti-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ~/study/docker/mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
      - MONGO_INITDB_DATABASE=noti
    restart: always