spring:
  application:
    name:
      kafka-notification-consumer
  profiles:
    active: local
    include: event
  data:
    mongodb:
      host: localhost
      port: 27017
      database: noti
      username: local
      password: local
      authentication-database: admin