spring:
  application:
    name:
      kafka-notification-api
  profiles:
    active: local
    include: redis
  data:
    redis:
      host: localhost
      port: 16379
    mongodb:
      host: localhost
      port: 27017
      database: noti
      username: local
      password: local
      authentication-database: admin