services:
  mongodb:
    image: mongo:6.0.16
    container_name: noti-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ~/study/docker/mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
      - MONGO_INITDB_DATABASE=noti
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.10
    container_name: noti-zookeeper
    ports:
      - '12181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.10
    container_name: noti-kafka
    depends_on:
      - zookeeper
    ports:
      - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
