spring:
  application:
    name:
      kafka-notification-core
  data:
    mongodb:
      host: localhost
      port: 27017
      database: noti
      username: local
      password: local
      authentication-database: admin
    redis:
      host: localhost
      port: 16379




